### ISSUE TITLE
String operators

### ISSUE THREAD

**Issue by Slakah** [typelevel/case-insensitive#27]
Would we want to add some of the standard utility string function as in [`StringLike`](https://www.scala-lang.org/api/2.12.6/scala/collection/immutable/StringLike.html).

Maybe a `.transform` function could be useful. The usual `naming things is hard` warning, would be interested in other ideas.

```scala
  def trim: CIString = transform(_.trim)
  def transform(f: String => String): CIString = CIString(f(toString))
```

**Comment by rossabaker** [comment]
`.trim` seems nice.  Someone on Twitter asked whether whitespace should be automatically trimmed.  I don't think so, but since you're the second to bring trimming up, I'm happy to make it convenient.

Going all in and extending `StringLike` is problematic because of `Char` instead of (non yet written) `CIChar`, as well as entangling us in Scala's evolving collection API.

Any other functions you'd like to build on `transform`?  I don't see anything wrong with it, but API is forever, so I want to be sure it's carrying its weight.

**Comment by Slakah** [comment]
Appreciate the great feedback @rossabaker !

You're right, I think `.trim` is the only nice to have atm.

**Comment by hamnis** [comment]
`isEmpty` and `nonEmpty` might be useful

**Comment by rossabaker** [comment]
Yeah, those seem safe and useful, too.
